name: unstack

image_shape: &image_shape [3, 96, 96]
shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  obs:
    image:
      shape: *image_shape
      type: rgb
    eef_pos:
      shape: [3]
      type: low_dim
    gripper_open:
      shape: [3]
      type: low_dim
  action:
    shape: [2]

env_runner:
  _target_: diffusion_policy.env_runner.fake_runner.FakeRunner

dataset:
  _target_: diffusion_policy.dataset.unstack_dataset.UnstackDataset
  zarr_path: data/unstack/unstack_cloud_new_small.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: 90
